/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.mantenimiento;

import bd.DAOMantenimiento;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.Mantenimiento;

/**
 *
 * @author Franco
 */
public class ActualizarMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarMantenimiento
     */
    private Integer selectedIdMantenimiento = null;

    ;

    public ActualizarMantenimiento() {
        initComponents();
        spnFecha.setModel(new javax.swing.SpinnerDateModel(
                new java.util.Date(), // valor inicial
                null, // sin límite inferior
                null, // sin límite superior
                java.util.Calendar.DAY_OF_MONTH // incremento por día
        ));
        // Formato visible yyyy-MM-dd
        spnFecha.setEditor(new javax.swing.JSpinner.DateEditor(spnFecha, "yyyy-MM-dd"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimientos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtKilometraje = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbTipoMantenimiento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la ID del camion:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblMantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Camion", "Fecha", "Tipo", "Descripcion", "Kilometraje"
            }
        ));
        jScrollPane1.setViewportView(tblMantenimientos);

        jLabel2.setText("Ingrese los datos:");

        jLabel3.setText("Fecha del mantenimiento");

        jLabel5.setText("Descripcion");

        jLabel6.setText("Kilometraje");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de mantenimiento");

        cbTipoMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventino", "Correctivo" }));
        cbTipoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String filtro = txtBuscar.getText().trim();
            if (filtro.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese ID de mantenimiento o ID del camión.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                txtBuscar.requestFocus();
                return;
            }

            int val;
            try {
                val = Integer.parseInt(filtro);
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "El filtro debe ser numérico.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                txtBuscar.requestFocus();
                return;
            }

            bd.DAOMantenimiento dao = new bd.DAOMantenimiento();
            model.Mantenimiento m = dao.findById(val);
            if (m == null) {
                m = dao.findByCamion(val); // intenta por id_camion
            }
            if (m == null) {
                limpiarCampos();
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron mantenimientos para el filtro.", "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            selectedIdMantenimiento = m.getId();

            // Poblar tabla (una fila)
            javax.swing.table.DefaultTableModel modelTbl = new javax.swing.table.DefaultTableModel();
            modelTbl.addColumn("ID");
            modelTbl.addColumn("ID Camión");
            modelTbl.addColumn("Fecha");
            modelTbl.addColumn("Tipo");
            modelTbl.addColumn("Descripción");
            modelTbl.addColumn("Kilometraje");
            Object[] fila = {m.getId(), m.getIdCamion(), m.getFecha(), m.getTipo(), m.getDescripcion(), m.getKilometraje()};
            modelTbl.addRow(fila);
            tblMantenimientos.setModel(modelTbl);
            tblMantenimientos.setAutoCreateRowSorter(true);

            // Poblar campos para edición
            if (m.getFecha() != null) {
                spnFecha.setValue(new java.util.Date(m.getFecha().getTime()));
            }
            if (m.getTipo() != null) {
                cbTipoMantenimiento.setSelectedItem(m.getTipo());
            }
            txtDescripcion.setText(m.getDescripcion() == null ? "" : m.getDescripcion());
            txtKilometraje.setText(m.getKilometraje() == null ? "" : String.valueOf(m.getKilometraje()));

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (selectedIdMantenimiento == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero busque y seleccione un mantenimiento para actualizar.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Fecha
            Object valFecha = spnFecha.getValue();
            java.sql.Date fechaSql;
            if (valFecha instanceof java.util.Date) {
                fechaSql = new java.sql.Date(((java.util.Date) valFecha).getTime());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Fecha inválida.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tipo
            String tipo = cbTipoMantenimiento.getSelectedItem() == null ? "" : cbTipoMantenimiento.getSelectedItem().toString().trim();
            if (tipo.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione el tipo de mantenimiento.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                cbTipoMantenimiento.requestFocus();
                return;
            }

            // Descripción
            String descripcion = txtDescripcion.getText().trim();
            if (descripcion.isEmpty()) {
                descripcion = null;
            }

            // Kilometraje
            String kmStr = txtKilometraje.getText().trim();
            Integer kilometraje = null;
            if (!kmStr.isEmpty()) {
                try {
                    kilometraje = Integer.parseInt(kmStr);
                } catch (NumberFormatException nfe) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Kilometraje inválido. Debe ser un número entero.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
                    txtKilometraje.requestFocus();
                    return;
                }
            }

            // Construir objeto modelo y actualizar vía DAO
            model.Mantenimiento m = new model.Mantenimiento();
            m.setId(selectedIdMantenimiento);
            m.setFecha(fechaSql);
            m.setTipo(tipo);
            m.setDescripcion(descripcion);
            m.setKilometraje(kilometraje);

            bd.DAOMantenimiento dao = new bd.DAOMantenimiento();
            dao.update(m);

            javax.swing.JOptionPane.showMessageDialog(this, "Mantenimiento actualizado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Reflejar cambios en la tabla
            if (tblMantenimientos.getRowCount() > 0) {
                tblMantenimientos.setValueAt(fechaSql, 0, 2);
                tblMantenimientos.setValueAt(tipo, 0, 3);
                tblMantenimientos.setValueAt(descripcion, 0, 4);
                tblMantenimientos.setValueAt(kilometraje, 0, 5);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbTipoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoMantenimientoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        GestorMantenimiento gestorMantenimiento = new GestorMantenimiento();
        gestorMantenimiento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbTipoMantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JTable tblMantenimientos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtKilometraje;
    // End of variables declaration//GEN-END:variables
private String escape(String s) {
        if (s == null) {
            return null;
        }
        return s.replace("'", "''");
    }

    private void limpiarCampos() {
        txtBuscar.setText("");
        spnFecha.setValue(new java.util.Date());
        if (cbTipoMantenimiento.getItemCount() > 0) {
            cbTipoMantenimiento.setSelectedIndex(0);
        }
        txtDescripcion.setText("");
        txtKilometraje.setText("");
        selectedIdMantenimiento = null;
        tblMantenimientos.setModel(new javax.swing.table.DefaultTableModel());
    }
}
