/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.camiones;

import bd.DAOCamion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Camion;

/**
 *
 * @author bevod
 */
public class AgregarCamion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCamion
     */
    public AgregarCamion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarCamion = new javax.swing.JLabel();
        lblPatente = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        lblKilometraje = new javax.swing.JLabel();
        txtKilometraje = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgregarCamion.setText("Agregar Camion");

        lblPatente.setText("Patente");

        lblMarca.setText("Marca");

        lblModelo.setText("Modelo");

        lblAno.setText("Año");

        lblKilometraje.setText("Kilometraje");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOk)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblKilometraje)
                                .addComponent(lblAno)
                                .addComponent(lblModelo)
                                .addComponent(lblPatente)
                                .addComponent(txtPatente)
                                .addComponent(lblMarca)
                                .addComponent(txtMarca)
                                .addComponent(txtModelo)
                                .addComponent(txtAno)
                                .addComponent(txtKilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addComponent(lblAgregarCamion))))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAgregarCamion)
                .addGap(26, 26, 26)
                .addComponent(lblPatente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblKilometraje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validarFormulario() {
        String patente = txtPatente.getText().trim().toUpperCase();
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String anioStr = txtAno.getText().trim();
        String kmStr = txtKilometraje.getText().trim();

        if (patente.isEmpty()) {
            mostrarError(txtPatente, "La patente es obligatoria");
            return false;
        }
        if (!patente.matches("^[A-Z0-9-]{4,8}$")) {
            mostrarError(txtPatente, "Patente inválida (solo letras, números y guión, 4-8 caracteres)");
            return false;
        }

        if (marca.length() > 50) {
            mostrarError(txtMarca, "Marca demasiado larga (máx. 50 caracteres)");
            return false;
        }
        if (modelo.length() > 50) {
            mostrarError(txtModelo, "Modelo demasiado largo (máx. 50 caracteres)");
            return false;
        }

        if (anioStr.isEmpty()) {
            mostrarError(txtAno, "El año es obligatorio");
            return false;
        }
        int anio;
        try {
            anio = Integer.parseInt(anioStr);
        } catch (NumberFormatException e) {
            mostrarError(txtAno, "Año debe ser un número entero");
            return false;
        }
        int anioActual = java.time.Year.now().getValue();
        if (anio < 1900 || anio > anioActual + 1) {
            mostrarError(txtAno, "Año fuera de rango (" + 1900 + " - " + (anioActual + 1) + ")");
            return false;
        }

        if (kmStr.isEmpty()) {
            mostrarError(txtKilometraje, "El kilometraje es obligatorio");
            return false;
        }
        int km;
        try {
            km = Integer.parseInt(kmStr);
        } catch (NumberFormatException e) {
            mostrarError(txtKilometraje, "Kilometraje debe ser un número entero");
            return false;
        }
        if (km < 0) {
            mostrarError(txtKilometraje, "Kilometraje no puede ser negativo");
            return false;
        }

        // Si todo OK, limpiar errores visuales
        limpiarErrores();
        return true;
    }

    private void mostrarError(javax.swing.JComponent campo, String mensaje) {
        campo.setToolTipText(mensaje);
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
        campo.requestFocus();
    }

    private void limpiarErrores() {
        javax.swing.border.Border defaultBorder = javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY);
        txtPatente.setBorder(defaultBorder);
        txtPatente.setToolTipText(null);
        txtMarca.setBorder(defaultBorder);
        txtMarca.setToolTipText(null);
        txtModelo.setBorder(defaultBorder);
        txtModelo.setToolTipText(null);
        txtAno.setBorder(defaultBorder);
        txtAno.setToolTipText(null);
        txtKilometraje.setBorder(defaultBorder);
        txtKilometraje.setToolTipText(null);
    }

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            if (!validarFormulario()) {
                return;
            }
            String Patente = txtPatente.getText().trim().toUpperCase();
            String Marca = txtMarca.getText().trim();
            String Modelo = txtModelo.getText().trim();
            int Anio = Integer.parseInt(txtAno.getText().trim());
            int Kilometraje = Integer.parseInt(txtKilometraje.getText().trim());

            DAOCamion oDAOCamion = new DAOCamion();

            if (oDAOCamion.patenteExiste(Patente)) {
                JOptionPane.showMessageDialog(this, "La patente ya está registrada en la base de datos.", "Patente duplicada", JOptionPane.WARNING_MESSAGE);
                txtPatente.requestFocus();
                return;
            }
            
            Camion nuevoCamion = new Camion();
            nuevoCamion.setPatenteCamion(Patente);
            nuevoCamion.setMarca(Marca);
            nuevoCamion.setModelo(Modelo);
            nuevoCamion.setAnio(Anio);
            nuevoCamion.setKilometraje(Kilometraje);

            oDAOCamion.crearCamion(nuevoCamion);

            JOptionPane.showMessageDialog(this, "Camion Agregado Correctamente!");

            GestionCamiones gestionCamiones = new GestionCamiones();
            gestionCamiones.setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(AgregarCamion.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCamion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblAgregarCamion;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblKilometraje;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
