/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.camiones;

import app.MenuPrincipal;

/**
 *
 * @author bevod
 */
public class GestionCamiones extends javax.swing.JFrame {

    /**
     * Creates new form GestionCamiones
     */
    public GestionCamiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        btnAgregarCamion = new javax.swing.JButton();
        btnVerCamiones = new javax.swing.JButton();
        btnActualizarCamion = new javax.swing.JButton();
        btnEliminarCamion = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblUsuario.setText("Gestion de Camiones");

        btnAgregarCamion.setBackground(new java.awt.Color(100, 149, 237));
        btnAgregarCamion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAgregarCamion.setForeground(new java.awt.Color(242, 235, 227));
        btnAgregarCamion.setText("Agregar Camion");
        btnAgregarCamion.setBorderPainted(false);
        btnAgregarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCamionActionPerformed(evt);
            }
        });

        btnVerCamiones.setBackground(new java.awt.Color(100, 149, 237));
        btnVerCamiones.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnVerCamiones.setForeground(new java.awt.Color(242, 235, 227));
        btnVerCamiones.setText("Ver Camiones");
        btnVerCamiones.setBorderPainted(false);
        btnVerCamiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerCamionesMouseClicked(evt);
            }
        });
        btnVerCamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCamionesActionPerformed(evt);
            }
        });

        btnActualizarCamion.setBackground(new java.awt.Color(100, 149, 237));
        btnActualizarCamion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnActualizarCamion.setForeground(new java.awt.Color(242, 235, 227));
        btnActualizarCamion.setText("Actualizar Camion");
        btnActualizarCamion.setBorderPainted(false);
        btnActualizarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCamionActionPerformed(evt);
            }
        });

        btnEliminarCamion.setBackground(new java.awt.Color(100, 149, 237));
        btnEliminarCamion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEliminarCamion.setForeground(new java.awt.Color(242, 235, 227));
        btnEliminarCamion.setText("Eliminar Camion");
        btnEliminarCamion.setBorderPainted(false);
        btnEliminarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCamionActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCerrarSesion.setText("Volver");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion)
                    .addComponent(lblUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAgregarCamion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarCamion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCamion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerCamiones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblUsuario)
                .addGap(49, 49, 49)
                .addComponent(btnAgregarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnVerCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnActualizarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnEliminarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCerrarSesion)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCamionesActionPerformed
        VerCamiones verCamiones = new VerCamiones();
        verCamiones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerCamionesActionPerformed

    private void btnActualizarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCamionActionPerformed
        ActualizarCamiones actualizarCamiones = new ActualizarCamiones();
        actualizarCamiones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarCamionActionPerformed

    private void btnAgregarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCamionActionPerformed
        AgregarCamion agregarCamion = new AgregarCamion();
        agregarCamion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarCamionActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVerCamionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCamionesMouseClicked
        
    }//GEN-LAST:event_btnVerCamionesMouseClicked

    private void btnEliminarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCamionActionPerformed
        EliminarCamion eliminarCamion = new EliminarCamion();
        eliminarCamion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarCamionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCamion;
    private javax.swing.JButton btnAgregarCamion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminarCamion;
    private javax.swing.JButton btnVerCamiones;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
