/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.camiones;

import app.MenuPrincipal;
import bd.DAOCamion;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Camion;
import model.Sesion;

/**
 *
 * @author bevod
 */
public class MisCamiones extends javax.swing.JFrame {
    
    private Timer refresco;

    public MisCamiones() {
        try {
            initComponents();
            MostrarCamionesEnTabla();
            iniciarRefresco();
        } catch (SQLException ex) {
            Logger.getLogger(MisCamiones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }

    private void iniciarRefresco() {
        refresco = new Timer(5000, e -> {
            try {
                MostrarCamionesEnTabla();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });

        refresco.start();
    }

    private void MostrarCamionesEnTabla() throws SQLException {
        String[] columnas = {"ID CAMION", "Patente", "Marca", "Anio", "Kilometraje", "Temperatura", "Conductor"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        if (Sesion.haySesion()) {
            int idLogueado = Sesion.getUsuario().getIdUsuario();

            DAOCamion daoCamion = new DAOCamion();

            ArrayList<Camion> camiones = daoCamion.getListaCamionesPorConductor(idLogueado);

            for (Camion c : camiones) {
                
                double actual = c.getTemperatura();
                
                if(actual == 0) {
                    actual = 70;
                }
                
                double nuevaTemp = SimuladorTemperatura.generarTemperatura(actual, c.getKilometraje());
                
                c.setTemperatura(nuevaTemp);
                
                Object[] fila = {
                    c.getIdCamion(),
                    c.getPatenteCamion(),
                    c.getMarca(),
                    c.getAnio(),
                    c.getKilometraje(),
                    String.format("%.1f °C", c.getTemperatura()),
                    Sesion.getUsuario().getNombre()
                };
                modelo.addRow(fila);
            }
        }

        tblCamiones.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCamiones = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        txtKilometraje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCamiones.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblCamiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCamiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCamionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCamiones);

        btnVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtKilometraje.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Kilometraje");

        btnAnadir.setBackground(new java.awt.Color(100, 149, 237));
        btnAnadir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(242, 235, 227));
        btnAnadir.setText("Añadir");
        btnAnadir.setBorderPainted(false);
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnadir)
                            .addComponent(txtKilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCamionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCamionesMouseClicked


    }//GEN-LAST:event_tblCamionesMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed

        int fila = tblCamiones.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un camión de la lista.");
            return;
        }

        int idCamion = (int) tblCamiones.getValueAt(fila, 0);

        try {

            int kmsNuevos = Integer.parseInt(txtKilometraje.getText().trim());

            DAOCamion dao = new DAOCamion();

            dao.sumarKilometraje(idCamion, kmsNuevos);

            model.Camion c = dao.findById(idCamion);
            int totalKM = c.getKilometraje();

            String mensaje = Alerta.generarMensajeAlerta(c.getPatenteCamion(), totalKM);

            if (mensaje != null) {

                JOptionPane.showMessageDialog(this,
                        mensaje,
                        "Alerta de Seguridad",
                        JOptionPane.WARNING_MESSAGE);

            } else {

                JOptionPane.showMessageDialog(this, "Kilometraje actualizado (+ " + kmsNuevos + " km)");
            }

            txtKilometraje.setText("");
            MostrarCamionesEnTabla();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCamiones;
    private javax.swing.JTextField txtKilometraje;
    // End of variables declaration//GEN-END:variables
}
